"use client";

import ProtectedRoute from "@/components/ProtectedRoute";
import { useLanguage } from "@/context/LanguageContext";
import { financeService, FinanceDashboardResponse } from "@/services/finance/financeService";
import Link from "next/link";
import { useEffect, useState } from "react";
import {
  BarChart3,
  DollarSign,
  FileText,
  Landmark,
  Loader2,
  Wallet,
} from "lucide-react";

function getErrorMessage(err: unknown) {
  if (
    typeof err === "object" &&
    err !== null &&
    "response" in err &&
    typeof err.response === "object" &&
    err.response !== null &&
    "data" in err.response &&
    typeof err.response.data === "object" &&
    err.response.data !== null &&
    "message" in err.response.data &&
    typeof err.response.data.message === "string"
  ) {
    return err.response.data.message;
  }
  return "Failed to load finance dashboard";
}

const surface =
  "rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900";

const quickLinks = [
  {
    label: "Receivables",
    desc: "Follow customer-side receivable exposure.",
    href: "/dashboard/finance/receivables",
    icon: FileText,
  },
  {
    label: "Payables",
    desc: "Review supplier invoices and outstanding amounts.",
    href: "/dashboard/finance/payables",
    icon: DollarSign,
  },
  {
    label: "Treasury",
    desc: "See inflow, outflow, and near-term due amounts.",
    href: "/dashboard/finance/treasury",
    icon: Wallet,
  },
  {
    label: "Journal",
    desc: "Review accounting entries generated by the ERP.",
    href: "/dashboard/finance/journal",
    icon: FileText,
  },
  {
    label: "Ledger",
    desc: "Inspect account balances and debit-credit movements.",
    href: "/dashboard/finance/accounts",
    icon: Landmark,
  },
  {
    label: "Reports",
    desc: "Open balance sheet and P&L views.",
    href: "/dashboard/finance/reports",
    icon: BarChart3,
  },
];

export default function FinanceDashboardPage() {
  const { t, language } = useLanguage();
  const text =
    language === "fr"
      ? {
          title: "Tableau de bord Finance",
          subtitle: "Visibilité financière alimentée par les événements Achat et Commercial.",
          quickLinks: [
            { label: "Créances", desc: "Suivez l'exposition côté clients.", href: "/dashboard/finance/receivables", icon: FileText },
            { label: "Dettes", desc: "Consultez les factures fournisseurs et les montants restants.", href: "/dashboard/finance/payables", icon: DollarSign },
            { label: "Trésorerie", desc: "Voyez les encaissements, décaissements et échéances proches.", href: "/dashboard/finance/treasury", icon: Wallet },
            { label: "Journal", desc: "Consultez les écritures comptables générées par l'ERP.", href: "/dashboard/finance/journal", icon: FileText },
            { label: "Grand livre", desc: "Analysez les soldes de comptes et les mouvements débit-crédit.", href: "/dashboard/finance/accounts", icon: Landmark },
            { label: "Rapports", desc: "Ouvrez le bilan et le compte de résultat.", href: "/dashboard/finance/reports", icon: BarChart3 },
          ],
          customerReceivables: "Créances clients",
          supplierPayables: "Dettes fournisseurs",
          paidOut: "Décaissements",
          recognizedRevenue: "Chiffre d'affaires reconnu",
          netExpectedCash: "Trésorerie nette attendue",
          overduePayables: "Dettes en retard",
          openPayables: "Dettes ouvertes",
          openReceivables: "Créances ouvertes",
          navTitle: "Navigation Finance",
          navSubtitle: "Ouvrez la vue finance sur laquelle vous voulez travailler.",
        }
      : {
          title: `${t("financeModule")} Dashboard`,
          subtitle: "Finance visibility built from purchase and commercial events.",
          quickLinks,
          customerReceivables: "Customer Receivables",
          supplierPayables: "Supplier Payables",
          paidOut: "Paid Out",
          recognizedRevenue: "Recognized Revenue",
          netExpectedCash: "Net Expected Cash",
          overduePayables: "Overdue Payables",
          openPayables: "Open Payables",
          openReceivables: "Open Receivables",
          navTitle: "Finance Navigation",
          navSubtitle: "Open the finance view you want to work on.",
        };
  const [dashboard, setDashboard] = useState<FinanceDashboardResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setError("");
        setDashboard(await financeService.getDashboard());
      } catch (err: unknown) {
        setError(getErrorMessage(err));
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const totals = dashboard?.totals;

  return (
    <ProtectedRoute allowedRoles={["ADMIN", "FINANCE_MANAGER"]}>
      <div className="space-y-6">
        <div>
          <p className="mb-2 text-[11px] font-medium uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">
            {t("financeModule")} · ERP
          </p>
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 dark:bg-slate-800">
              <DollarSign size={18} className="text-slate-600 dark:text-slate-300" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight text-slate-950 dark:text-white">
                {text.title}
              </h1>
              <p className="text-sm text-slate-500 dark:text-slate-400">
                {text.subtitle}
              </p>
            </div>
          </div>
        </div>

        {error ? (
          <div className="rounded-3xl border border-rose-200 bg-rose-50 px-6 py-4 text-sm text-rose-600 dark:border-rose-900/40 dark:bg-rose-950/20 dark:text-rose-400">
            {error}
          </div>
        ) : null}

        {loading ? (
          <div className={`${surface} flex items-center justify-center gap-2 py-16 text-sm text-slate-500 dark:text-slate-400`}>
            <Loader2 size={16} className="animate-spin" />
            {t("loading")}
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
              {[
                {
                  label: text.customerReceivables,
                  value: `${(totals?.totalReceivables || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND`,
                  icon: DollarSign,
                  bg: "bg-emerald-50 dark:bg-emerald-950/30",
                  color: "text-emerald-600 dark:text-emerald-400",
                },
                {
                  label: text.supplierPayables,
                  value: `${(totals?.totalPayablesOutstanding || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND`,
                  icon: Wallet,
                  bg: "bg-blue-50 dark:bg-blue-950/30",
                  color: "text-blue-600 dark:text-blue-400",
                },
                {
                  label: text.paidOut,
                  value: `${(totals?.totalPaidOut || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND`,
                  icon: Landmark,
                  bg: "bg-violet-50 dark:bg-violet-950/30",
                  color: "text-violet-600 dark:text-violet-400",
                },
                {
                  label: text.recognizedRevenue,
                  value: `${(totals?.recognizedRevenue || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND`,
                  icon: BarChart3,
                  bg: "bg-rose-50 dark:bg-rose-950/30",
                  color: "text-rose-600 dark:text-rose-400",
                },
              ].map((kpi) => (
                <div key={kpi.label} className={`${surface} flex items-center gap-4 px-5 py-5`}>
                  <div className={`rounded-2xl p-3 ${kpi.bg}`}>
                    <kpi.icon size={16} className={kpi.color} />
                  </div>
                  <div>
                    <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">
                      {kpi.label}
                    </p>
                    <p className="mt-1 text-lg font-bold tracking-tight text-slate-950 dark:text-white">
                      {kpi.value}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
              {[
                { label: text.netExpectedCash, value: `${(totals?.netExpectedCash || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND` },
                { label: text.overduePayables, value: String(totals?.overduePayables || 0) },
                { label: text.openPayables, value: `${(totals?.totalPayablesOutstanding || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND` },
                { label: text.openReceivables, value: `${(totals?.totalReceivables || 0).toLocaleString("fr-TN", { minimumFractionDigits: 2 })} TND` },
              ].map((item) => (
                <div key={item.label} className={`${surface} px-6 py-5`}>
                  <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-400 dark:text-slate-500">
                    {item.label}
                  </p>
                  <p className="mt-2 text-2xl font-bold tracking-tight text-slate-950 dark:text-white">
                    {item.value}
                  </p>
                </div>
              ))}
            </div>

            <div className={`${surface} overflow-hidden`}>
              <div className="border-b border-slate-200 px-6 py-5 dark:border-slate-800">
                <h2 className="text-lg font-semibold text-slate-950 dark:text-white">
                  {text.navTitle}
                </h2>
                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
                  {text.navSubtitle}
                </p>
              </div>

              <div className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-3">
                {text.quickLinks.map((link) => (
                  <Link
                    key={link.href}
                    href={link.href}
                    className="rounded-2xl border border-slate-200 bg-slate-50 px-5 py-5 transition hover:bg-slate-100 dark:border-slate-800 dark:bg-slate-950 dark:hover:bg-slate-900"
                  >
                    <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white dark:bg-slate-900">
                      <link.icon size={18} className="text-slate-600 dark:text-slate-300" />
                    </div>
                    <h3 className="mt-4 text-base font-semibold text-slate-950 dark:text-white">
                      {link.label}
                    </h3>
                    <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
                      {link.desc}
                    </p>
                  </Link>
                ))}
              </div>
            </div>
          </>
        )}
      </div>
    </ProtectedRoute>
  );
}
